import { Philosopher } from "next/font/google";
import "./globals.css";
import WindowTitlebar from "../components/WindowTitlebar";
// import Buildings from "@/app/buildings/page";
import {ReduxProvider} from "@/lib/provider";

const philosopher = Philosopher({
    weight: ["400", "700"],
    subsets: ['cyrillic']
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={philosopher.className}>
          <WindowTitlebar/>
          <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
